// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDetailTransaction = "detail_transaction"

// DetailTransaction mapped from table <detail_transaction>
type DetailTransaction struct {
	ID             string       `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	TransactionID  string       `gorm:"column:transaction_id;not null" json:"transaction_id"`
	ProductsliceID string       `gorm:"column:productslice_id;not null" json:"productslice_id"`
	Quantity       float64      `gorm:"column:quantity;not null" json:"quantity"`
	ProductSlice   Productslice `gorm:"foreignKey:productslice_id" json:"product_slice"`
}

// TableName DetailTransaction's table name
func (*DetailTransaction) TableName() string {
	return TableNameDetailTransaction
}
