// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProductslice = "productslice"

// Productslice mapped from table <productslice>
type Productslice struct {
	ID        string  `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	ProductID string  `gorm:"column:product_id;not null" json:"product_id"`
	Slice     string  `gorm:"column:slice;not null" json:"slice"`
	Product   Product `gorm:"foreignKey:product_id" json:"product"`
}

// TableName Productslice's table name
func (*Productslice) TableName() string {
	return TableNameProductslice
}
