// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWishlist = "wishlist"

// Wishlist mapped from table <wishlist>
type Wishlist struct {
	UserID    string    `gorm:"column:user_id;primaryKey" json:"user_id"`
	ProductID string    `gorm:"column:product_id;primaryKey" json:"product_id"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	Product   Product   `gorm:"foreignKey:product_id" json:"product"`
	User      User      `gorm:"foreignKey:user_id" json:"user"`
}

// TableName Wishlist's table name
func (*Wishlist) TableName() string {
	return TableNameWishlist
}
