// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"KAIA-BE/model"
)

func newDetailTransaction(db *gorm.DB, opts ...gen.DOOption) detailTransaction {
	_detailTransaction := detailTransaction{}

	_detailTransaction.detailTransactionDo.UseDB(db, opts...)
	_detailTransaction.detailTransactionDo.UseModel(&model.DetailTransaction{})

	tableName := _detailTransaction.detailTransactionDo.TableName()
	_detailTransaction.ALL = field.NewAsterisk(tableName)
	_detailTransaction.ID = field.NewString(tableName, "id")
	_detailTransaction.TransactionID = field.NewString(tableName, "transaction_id")
	_detailTransaction.ProductsliceID = field.NewString(tableName, "productslice_id")
	_detailTransaction.Quantity = field.NewFloat64(tableName, "quantity")
	_detailTransaction.ProductSlice = detailTransactionHasOneProductSlice{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ProductSlice", "model.Productslice"),
		Product: struct {
			field.RelationField
			Admin struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("ProductSlice.Product", "model.Product"),
			Admin: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("ProductSlice.Product.Admin", "model.Admin"),
			},
		},
	}

	_detailTransaction.fillFieldMap()

	return _detailTransaction
}

type detailTransaction struct {
	detailTransactionDo

	ALL            field.Asterisk
	ID             field.String
	TransactionID  field.String
	ProductsliceID field.String
	Quantity       field.Float64
	ProductSlice   detailTransactionHasOneProductSlice

	fieldMap map[string]field.Expr
}

func (d detailTransaction) Table(newTableName string) *detailTransaction {
	d.detailTransactionDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d detailTransaction) As(alias string) *detailTransaction {
	d.detailTransactionDo.DO = *(d.detailTransactionDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *detailTransaction) updateTableName(table string) *detailTransaction {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewString(table, "id")
	d.TransactionID = field.NewString(table, "transaction_id")
	d.ProductsliceID = field.NewString(table, "productslice_id")
	d.Quantity = field.NewFloat64(table, "quantity")

	d.fillFieldMap()

	return d
}

func (d *detailTransaction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *detailTransaction) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 5)
	d.fieldMap["id"] = d.ID
	d.fieldMap["transaction_id"] = d.TransactionID
	d.fieldMap["productslice_id"] = d.ProductsliceID
	d.fieldMap["quantity"] = d.Quantity

}

func (d detailTransaction) clone(db *gorm.DB) detailTransaction {
	d.detailTransactionDo.ReplaceConnPool(db.Statement.ConnPool)
	d.ProductSlice.db = db.Session(&gorm.Session{Initialized: true})
	d.ProductSlice.db.Statement.ConnPool = db.Statement.ConnPool
	return d
}

func (d detailTransaction) replaceDB(db *gorm.DB) detailTransaction {
	d.detailTransactionDo.ReplaceDB(db)
	d.ProductSlice.db = db.Session(&gorm.Session{})
	return d
}

type detailTransactionHasOneProductSlice struct {
	db *gorm.DB

	field.RelationField

	Product struct {
		field.RelationField
		Admin struct {
			field.RelationField
		}
	}
}

func (a detailTransactionHasOneProductSlice) Where(conds ...field.Expr) *detailTransactionHasOneProductSlice {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a detailTransactionHasOneProductSlice) WithContext(ctx context.Context) *detailTransactionHasOneProductSlice {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a detailTransactionHasOneProductSlice) Session(session *gorm.Session) *detailTransactionHasOneProductSlice {
	a.db = a.db.Session(session)
	return &a
}

func (a detailTransactionHasOneProductSlice) Model(m *model.DetailTransaction) *detailTransactionHasOneProductSliceTx {
	return &detailTransactionHasOneProductSliceTx{a.db.Model(m).Association(a.Name())}
}

func (a detailTransactionHasOneProductSlice) Unscoped() *detailTransactionHasOneProductSlice {
	a.db = a.db.Unscoped()
	return &a
}

type detailTransactionHasOneProductSliceTx struct{ tx *gorm.Association }

func (a detailTransactionHasOneProductSliceTx) Find() (result *model.Productslice, err error) {
	return result, a.tx.Find(&result)
}

func (a detailTransactionHasOneProductSliceTx) Append(values ...*model.Productslice) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a detailTransactionHasOneProductSliceTx) Replace(values ...*model.Productslice) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a detailTransactionHasOneProductSliceTx) Delete(values ...*model.Productslice) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a detailTransactionHasOneProductSliceTx) Clear() error {
	return a.tx.Clear()
}

func (a detailTransactionHasOneProductSliceTx) Count() int64 {
	return a.tx.Count()
}

func (a detailTransactionHasOneProductSliceTx) Unscoped() *detailTransactionHasOneProductSliceTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type detailTransactionDo struct{ gen.DO }

type IDetailTransactionDo interface {
	gen.SubQuery
	Debug() IDetailTransactionDo
	WithContext(ctx context.Context) IDetailTransactionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDetailTransactionDo
	WriteDB() IDetailTransactionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDetailTransactionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDetailTransactionDo
	Not(conds ...gen.Condition) IDetailTransactionDo
	Or(conds ...gen.Condition) IDetailTransactionDo
	Select(conds ...field.Expr) IDetailTransactionDo
	Where(conds ...gen.Condition) IDetailTransactionDo
	Order(conds ...field.Expr) IDetailTransactionDo
	Distinct(cols ...field.Expr) IDetailTransactionDo
	Omit(cols ...field.Expr) IDetailTransactionDo
	Join(table schema.Tabler, on ...field.Expr) IDetailTransactionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDetailTransactionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDetailTransactionDo
	Group(cols ...field.Expr) IDetailTransactionDo
	Having(conds ...gen.Condition) IDetailTransactionDo
	Limit(limit int) IDetailTransactionDo
	Offset(offset int) IDetailTransactionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDetailTransactionDo
	Unscoped() IDetailTransactionDo
	Create(values ...*model.DetailTransaction) error
	CreateInBatches(values []*model.DetailTransaction, batchSize int) error
	Save(values ...*model.DetailTransaction) error
	First() (*model.DetailTransaction, error)
	Take() (*model.DetailTransaction, error)
	Last() (*model.DetailTransaction, error)
	Find() ([]*model.DetailTransaction, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DetailTransaction, err error)
	FindInBatches(result *[]*model.DetailTransaction, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DetailTransaction) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDetailTransactionDo
	Assign(attrs ...field.AssignExpr) IDetailTransactionDo
	Joins(fields ...field.RelationField) IDetailTransactionDo
	Preload(fields ...field.RelationField) IDetailTransactionDo
	FirstOrInit() (*model.DetailTransaction, error)
	FirstOrCreate() (*model.DetailTransaction, error)
	FindByPage(offset int, limit int) (result []*model.DetailTransaction, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDetailTransactionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d detailTransactionDo) Debug() IDetailTransactionDo {
	return d.withDO(d.DO.Debug())
}

func (d detailTransactionDo) WithContext(ctx context.Context) IDetailTransactionDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d detailTransactionDo) ReadDB() IDetailTransactionDo {
	return d.Clauses(dbresolver.Read)
}

func (d detailTransactionDo) WriteDB() IDetailTransactionDo {
	return d.Clauses(dbresolver.Write)
}

func (d detailTransactionDo) Session(config *gorm.Session) IDetailTransactionDo {
	return d.withDO(d.DO.Session(config))
}

func (d detailTransactionDo) Clauses(conds ...clause.Expression) IDetailTransactionDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d detailTransactionDo) Returning(value interface{}, columns ...string) IDetailTransactionDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d detailTransactionDo) Not(conds ...gen.Condition) IDetailTransactionDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d detailTransactionDo) Or(conds ...gen.Condition) IDetailTransactionDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d detailTransactionDo) Select(conds ...field.Expr) IDetailTransactionDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d detailTransactionDo) Where(conds ...gen.Condition) IDetailTransactionDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d detailTransactionDo) Order(conds ...field.Expr) IDetailTransactionDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d detailTransactionDo) Distinct(cols ...field.Expr) IDetailTransactionDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d detailTransactionDo) Omit(cols ...field.Expr) IDetailTransactionDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d detailTransactionDo) Join(table schema.Tabler, on ...field.Expr) IDetailTransactionDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d detailTransactionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDetailTransactionDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d detailTransactionDo) RightJoin(table schema.Tabler, on ...field.Expr) IDetailTransactionDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d detailTransactionDo) Group(cols ...field.Expr) IDetailTransactionDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d detailTransactionDo) Having(conds ...gen.Condition) IDetailTransactionDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d detailTransactionDo) Limit(limit int) IDetailTransactionDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d detailTransactionDo) Offset(offset int) IDetailTransactionDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d detailTransactionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDetailTransactionDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d detailTransactionDo) Unscoped() IDetailTransactionDo {
	return d.withDO(d.DO.Unscoped())
}

func (d detailTransactionDo) Create(values ...*model.DetailTransaction) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d detailTransactionDo) CreateInBatches(values []*model.DetailTransaction, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d detailTransactionDo) Save(values ...*model.DetailTransaction) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d detailTransactionDo) First() (*model.DetailTransaction, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DetailTransaction), nil
	}
}

func (d detailTransactionDo) Take() (*model.DetailTransaction, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DetailTransaction), nil
	}
}

func (d detailTransactionDo) Last() (*model.DetailTransaction, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DetailTransaction), nil
	}
}

func (d detailTransactionDo) Find() ([]*model.DetailTransaction, error) {
	result, err := d.DO.Find()
	return result.([]*model.DetailTransaction), err
}

func (d detailTransactionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DetailTransaction, err error) {
	buf := make([]*model.DetailTransaction, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d detailTransactionDo) FindInBatches(result *[]*model.DetailTransaction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d detailTransactionDo) Attrs(attrs ...field.AssignExpr) IDetailTransactionDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d detailTransactionDo) Assign(attrs ...field.AssignExpr) IDetailTransactionDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d detailTransactionDo) Joins(fields ...field.RelationField) IDetailTransactionDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d detailTransactionDo) Preload(fields ...field.RelationField) IDetailTransactionDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d detailTransactionDo) FirstOrInit() (*model.DetailTransaction, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DetailTransaction), nil
	}
}

func (d detailTransactionDo) FirstOrCreate() (*model.DetailTransaction, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DetailTransaction), nil
	}
}

func (d detailTransactionDo) FindByPage(offset int, limit int) (result []*model.DetailTransaction, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d detailTransactionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d detailTransactionDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d detailTransactionDo) Delete(models ...*model.DetailTransaction) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *detailTransactionDo) withDO(do gen.Dao) *detailTransactionDo {
	d.DO = *do.(*gen.DO)
	return d
}
