// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	Admin             *admin
	DetailTransaction *detailTransaction
	HeaderTransaction *headerTransaction
	Product           *product
	Productslice      *productslice
	User              *user
	Wishlist          *wishlist
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Admin = &Q.Admin
	DetailTransaction = &Q.DetailTransaction
	HeaderTransaction = &Q.HeaderTransaction
	Product = &Q.Product
	Productslice = &Q.Productslice
	User = &Q.User
	Wishlist = &Q.Wishlist
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		Admin:             newAdmin(db, opts...),
		DetailTransaction: newDetailTransaction(db, opts...),
		HeaderTransaction: newHeaderTransaction(db, opts...),
		Product:           newProduct(db, opts...),
		Productslice:      newProductslice(db, opts...),
		User:              newUser(db, opts...),
		Wishlist:          newWishlist(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Admin             admin
	DetailTransaction detailTransaction
	HeaderTransaction headerTransaction
	Product           product
	Productslice      productslice
	User              user
	Wishlist          wishlist
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		Admin:             q.Admin.clone(db),
		DetailTransaction: q.DetailTransaction.clone(db),
		HeaderTransaction: q.HeaderTransaction.clone(db),
		Product:           q.Product.clone(db),
		Productslice:      q.Productslice.clone(db),
		User:              q.User.clone(db),
		Wishlist:          q.Wishlist.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		Admin:             q.Admin.replaceDB(db),
		DetailTransaction: q.DetailTransaction.replaceDB(db),
		HeaderTransaction: q.HeaderTransaction.replaceDB(db),
		Product:           q.Product.replaceDB(db),
		Productslice:      q.Productslice.replaceDB(db),
		User:              q.User.replaceDB(db),
		Wishlist:          q.Wishlist.replaceDB(db),
	}
}

type queryCtx struct {
	Admin             IAdminDo
	DetailTransaction IDetailTransactionDo
	HeaderTransaction IHeaderTransactionDo
	Product           IProductDo
	Productslice      IProductsliceDo
	User              IUserDo
	Wishlist          IWishlistDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Admin:             q.Admin.WithContext(ctx),
		DetailTransaction: q.DetailTransaction.WithContext(ctx),
		HeaderTransaction: q.HeaderTransaction.WithContext(ctx),
		Product:           q.Product.WithContext(ctx),
		Productslice:      q.Productslice.WithContext(ctx),
		User:              q.User.WithContext(ctx),
		Wishlist:          q.Wishlist.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
