// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"KAIA-BE/model"
)

func newProductslice(db *gorm.DB, opts ...gen.DOOption) productslice {
	_productslice := productslice{}

	_productslice.productsliceDo.UseDB(db, opts...)
	_productslice.productsliceDo.UseModel(&model.Productslice{})

	tableName := _productslice.productsliceDo.TableName()
	_productslice.ALL = field.NewAsterisk(tableName)
	_productslice.ID = field.NewString(tableName, "id")
	_productslice.ProductID = field.NewString(tableName, "product_id")
	_productslice.Slice = field.NewString(tableName, "slice")
	_productslice.Price = field.NewFloat64(tableName, "price")

	_productslice.fillFieldMap()

	return _productslice
}

type productslice struct {
	productsliceDo

	ALL       field.Asterisk
	ID        field.String
	ProductID field.String
	Slice     field.String
	Price     field.Float64

	fieldMap map[string]field.Expr
}

func (p productslice) Table(newTableName string) *productslice {
	p.productsliceDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productslice) As(alias string) *productslice {
	p.productsliceDo.DO = *(p.productsliceDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productslice) updateTableName(table string) *productslice {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewString(table, "id")
	p.ProductID = field.NewString(table, "product_id")
	p.Slice = field.NewString(table, "slice")
	p.Price = field.NewFloat64(table, "price")

	p.fillFieldMap()

	return p
}

func (p *productslice) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productslice) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["id"] = p.ID
	p.fieldMap["product_id"] = p.ProductID
	p.fieldMap["slice"] = p.Slice
	p.fieldMap["price"] = p.Price
}

func (p productslice) clone(db *gorm.DB) productslice {
	p.productsliceDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productslice) replaceDB(db *gorm.DB) productslice {
	p.productsliceDo.ReplaceDB(db)
	return p
}

type productsliceDo struct{ gen.DO }

type IProductsliceDo interface {
	gen.SubQuery
	Debug() IProductsliceDo
	WithContext(ctx context.Context) IProductsliceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProductsliceDo
	WriteDB() IProductsliceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProductsliceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProductsliceDo
	Not(conds ...gen.Condition) IProductsliceDo
	Or(conds ...gen.Condition) IProductsliceDo
	Select(conds ...field.Expr) IProductsliceDo
	Where(conds ...gen.Condition) IProductsliceDo
	Order(conds ...field.Expr) IProductsliceDo
	Distinct(cols ...field.Expr) IProductsliceDo
	Omit(cols ...field.Expr) IProductsliceDo
	Join(table schema.Tabler, on ...field.Expr) IProductsliceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProductsliceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProductsliceDo
	Group(cols ...field.Expr) IProductsliceDo
	Having(conds ...gen.Condition) IProductsliceDo
	Limit(limit int) IProductsliceDo
	Offset(offset int) IProductsliceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProductsliceDo
	Unscoped() IProductsliceDo
	Create(values ...*model.Productslice) error
	CreateInBatches(values []*model.Productslice, batchSize int) error
	Save(values ...*model.Productslice) error
	First() (*model.Productslice, error)
	Take() (*model.Productslice, error)
	Last() (*model.Productslice, error)
	Find() ([]*model.Productslice, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Productslice, err error)
	FindInBatches(result *[]*model.Productslice, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Productslice) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProductsliceDo
	Assign(attrs ...field.AssignExpr) IProductsliceDo
	Joins(fields ...field.RelationField) IProductsliceDo
	Preload(fields ...field.RelationField) IProductsliceDo
	FirstOrInit() (*model.Productslice, error)
	FirstOrCreate() (*model.Productslice, error)
	FindByPage(offset int, limit int) (result []*model.Productslice, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProductsliceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p productsliceDo) Debug() IProductsliceDo {
	return p.withDO(p.DO.Debug())
}

func (p productsliceDo) WithContext(ctx context.Context) IProductsliceDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productsliceDo) ReadDB() IProductsliceDo {
	return p.Clauses(dbresolver.Read)
}

func (p productsliceDo) WriteDB() IProductsliceDo {
	return p.Clauses(dbresolver.Write)
}

func (p productsliceDo) Session(config *gorm.Session) IProductsliceDo {
	return p.withDO(p.DO.Session(config))
}

func (p productsliceDo) Clauses(conds ...clause.Expression) IProductsliceDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productsliceDo) Returning(value interface{}, columns ...string) IProductsliceDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productsliceDo) Not(conds ...gen.Condition) IProductsliceDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productsliceDo) Or(conds ...gen.Condition) IProductsliceDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productsliceDo) Select(conds ...field.Expr) IProductsliceDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productsliceDo) Where(conds ...gen.Condition) IProductsliceDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productsliceDo) Order(conds ...field.Expr) IProductsliceDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productsliceDo) Distinct(cols ...field.Expr) IProductsliceDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productsliceDo) Omit(cols ...field.Expr) IProductsliceDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productsliceDo) Join(table schema.Tabler, on ...field.Expr) IProductsliceDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productsliceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProductsliceDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productsliceDo) RightJoin(table schema.Tabler, on ...field.Expr) IProductsliceDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productsliceDo) Group(cols ...field.Expr) IProductsliceDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productsliceDo) Having(conds ...gen.Condition) IProductsliceDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productsliceDo) Limit(limit int) IProductsliceDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productsliceDo) Offset(offset int) IProductsliceDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productsliceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProductsliceDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productsliceDo) Unscoped() IProductsliceDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productsliceDo) Create(values ...*model.Productslice) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productsliceDo) CreateInBatches(values []*model.Productslice, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productsliceDo) Save(values ...*model.Productslice) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productsliceDo) First() (*model.Productslice, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Productslice), nil
	}
}

func (p productsliceDo) Take() (*model.Productslice, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Productslice), nil
	}
}

func (p productsliceDo) Last() (*model.Productslice, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Productslice), nil
	}
}

func (p productsliceDo) Find() ([]*model.Productslice, error) {
	result, err := p.DO.Find()
	return result.([]*model.Productslice), err
}

func (p productsliceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Productslice, err error) {
	buf := make([]*model.Productslice, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productsliceDo) FindInBatches(result *[]*model.Productslice, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productsliceDo) Attrs(attrs ...field.AssignExpr) IProductsliceDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productsliceDo) Assign(attrs ...field.AssignExpr) IProductsliceDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productsliceDo) Joins(fields ...field.RelationField) IProductsliceDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productsliceDo) Preload(fields ...field.RelationField) IProductsliceDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productsliceDo) FirstOrInit() (*model.Productslice, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Productslice), nil
	}
}

func (p productsliceDo) FirstOrCreate() (*model.Productslice, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Productslice), nil
	}
}

func (p productsliceDo) FindByPage(offset int, limit int) (result []*model.Productslice, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productsliceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productsliceDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productsliceDo) Delete(models ...*model.Productslice) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productsliceDo) withDO(do gen.Dao) *productsliceDo {
	p.DO = *do.(*gen.DO)
	return p
}
