// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"KAIA-BE/model"
)

func newHeaderTransaction(db *gorm.DB, opts ...gen.DOOption) headerTransaction {
	_headerTransaction := headerTransaction{}

	_headerTransaction.headerTransactionDo.UseDB(db, opts...)
	_headerTransaction.headerTransactionDo.UseModel(&model.HeaderTransaction{})

	tableName := _headerTransaction.headerTransactionDo.TableName()
	_headerTransaction.ALL = field.NewAsterisk(tableName)
	_headerTransaction.ID = field.NewString(tableName, "id")
	_headerTransaction.Userid = field.NewString(tableName, "userid")
	_headerTransaction.Customername = field.NewString(tableName, "customername")
	_headerTransaction.Customeremail = field.NewString(tableName, "customeremail")
	_headerTransaction.Address = field.NewString(tableName, "address")
	_headerTransaction.City = field.NewString(tableName, "city")
	_headerTransaction.Postalcode = field.NewString(tableName, "postalcode")
	_headerTransaction.Totalprice = field.NewInt32(tableName, "totalprice")
	_headerTransaction.Items = field.NewString(tableName, "items")
	_headerTransaction.CreatedAt = field.NewTime(tableName, "created_at")
	_headerTransaction.CreatedBy = field.NewString(tableName, "created_by")
	_headerTransaction.DetailTransaction = headerTransactionHasManyDetailTransaction{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("DetailTransaction", "model.DetailTransaction"),
		ProductSlice: struct {
			field.RelationField
			Product struct {
				field.RelationField
				Admin struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("DetailTransaction.ProductSlice", "model.Productslice"),
			Product: struct {
				field.RelationField
				Admin struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("DetailTransaction.ProductSlice.Product", "model.Product"),
				Admin: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("DetailTransaction.ProductSlice.Product.Admin", "model.Admin"),
				},
			},
		},
	}

	_headerTransaction.Customer = headerTransactionHasOneCustomer{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Customer", "model.User"),
	}

	_headerTransaction.fillFieldMap()

	return _headerTransaction
}

type headerTransaction struct {
	headerTransactionDo

	ALL               field.Asterisk
	ID                field.String
	Userid            field.String
	Customername      field.String
	Customeremail     field.String
	Address           field.String
	City              field.String
	Postalcode        field.String
	Totalprice        field.Int32
	Items             field.String
	CreatedAt         field.Time
	CreatedBy         field.String
	DetailTransaction headerTransactionHasManyDetailTransaction

	Customer headerTransactionHasOneCustomer

	fieldMap map[string]field.Expr
}

func (h headerTransaction) Table(newTableName string) *headerTransaction {
	h.headerTransactionDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h headerTransaction) As(alias string) *headerTransaction {
	h.headerTransactionDo.DO = *(h.headerTransactionDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *headerTransaction) updateTableName(table string) *headerTransaction {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewString(table, "id")
	h.Userid = field.NewString(table, "userid")
	h.Customername = field.NewString(table, "customername")
	h.Customeremail = field.NewString(table, "customeremail")
	h.Address = field.NewString(table, "address")
	h.City = field.NewString(table, "city")
	h.Postalcode = field.NewString(table, "postalcode")
	h.Totalprice = field.NewInt32(table, "totalprice")
	h.Items = field.NewString(table, "items")
	h.CreatedAt = field.NewTime(table, "created_at")
	h.CreatedBy = field.NewString(table, "created_by")

	h.fillFieldMap()

	return h
}

func (h *headerTransaction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *headerTransaction) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 13)
	h.fieldMap["id"] = h.ID
	h.fieldMap["userid"] = h.Userid
	h.fieldMap["customername"] = h.Customername
	h.fieldMap["customeremail"] = h.Customeremail
	h.fieldMap["address"] = h.Address
	h.fieldMap["city"] = h.City
	h.fieldMap["postalcode"] = h.Postalcode
	h.fieldMap["totalprice"] = h.Totalprice
	h.fieldMap["items"] = h.Items
	h.fieldMap["created_at"] = h.CreatedAt
	h.fieldMap["created_by"] = h.CreatedBy

}

func (h headerTransaction) clone(db *gorm.DB) headerTransaction {
	h.headerTransactionDo.ReplaceConnPool(db.Statement.ConnPool)
	h.DetailTransaction.db = db.Session(&gorm.Session{Initialized: true})
	h.DetailTransaction.db.Statement.ConnPool = db.Statement.ConnPool
	h.Customer.db = db.Session(&gorm.Session{Initialized: true})
	h.Customer.db.Statement.ConnPool = db.Statement.ConnPool
	return h
}

func (h headerTransaction) replaceDB(db *gorm.DB) headerTransaction {
	h.headerTransactionDo.ReplaceDB(db)
	h.DetailTransaction.db = db.Session(&gorm.Session{})
	h.Customer.db = db.Session(&gorm.Session{})
	return h
}

type headerTransactionHasManyDetailTransaction struct {
	db *gorm.DB

	field.RelationField

	ProductSlice struct {
		field.RelationField
		Product struct {
			field.RelationField
			Admin struct {
				field.RelationField
			}
		}
	}
}

func (a headerTransactionHasManyDetailTransaction) Where(conds ...field.Expr) *headerTransactionHasManyDetailTransaction {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a headerTransactionHasManyDetailTransaction) WithContext(ctx context.Context) *headerTransactionHasManyDetailTransaction {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a headerTransactionHasManyDetailTransaction) Session(session *gorm.Session) *headerTransactionHasManyDetailTransaction {
	a.db = a.db.Session(session)
	return &a
}

func (a headerTransactionHasManyDetailTransaction) Model(m *model.HeaderTransaction) *headerTransactionHasManyDetailTransactionTx {
	return &headerTransactionHasManyDetailTransactionTx{a.db.Model(m).Association(a.Name())}
}

func (a headerTransactionHasManyDetailTransaction) Unscoped() *headerTransactionHasManyDetailTransaction {
	a.db = a.db.Unscoped()
	return &a
}

type headerTransactionHasManyDetailTransactionTx struct{ tx *gorm.Association }

func (a headerTransactionHasManyDetailTransactionTx) Find() (result []*model.DetailTransaction, err error) {
	return result, a.tx.Find(&result)
}

func (a headerTransactionHasManyDetailTransactionTx) Append(values ...*model.DetailTransaction) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a headerTransactionHasManyDetailTransactionTx) Replace(values ...*model.DetailTransaction) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a headerTransactionHasManyDetailTransactionTx) Delete(values ...*model.DetailTransaction) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a headerTransactionHasManyDetailTransactionTx) Clear() error {
	return a.tx.Clear()
}

func (a headerTransactionHasManyDetailTransactionTx) Count() int64 {
	return a.tx.Count()
}

func (a headerTransactionHasManyDetailTransactionTx) Unscoped() *headerTransactionHasManyDetailTransactionTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type headerTransactionHasOneCustomer struct {
	db *gorm.DB

	field.RelationField
}

func (a headerTransactionHasOneCustomer) Where(conds ...field.Expr) *headerTransactionHasOneCustomer {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a headerTransactionHasOneCustomer) WithContext(ctx context.Context) *headerTransactionHasOneCustomer {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a headerTransactionHasOneCustomer) Session(session *gorm.Session) *headerTransactionHasOneCustomer {
	a.db = a.db.Session(session)
	return &a
}

func (a headerTransactionHasOneCustomer) Model(m *model.HeaderTransaction) *headerTransactionHasOneCustomerTx {
	return &headerTransactionHasOneCustomerTx{a.db.Model(m).Association(a.Name())}
}

func (a headerTransactionHasOneCustomer) Unscoped() *headerTransactionHasOneCustomer {
	a.db = a.db.Unscoped()
	return &a
}

type headerTransactionHasOneCustomerTx struct{ tx *gorm.Association }

func (a headerTransactionHasOneCustomerTx) Find() (result *model.User, err error) {
	return result, a.tx.Find(&result)
}

func (a headerTransactionHasOneCustomerTx) Append(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a headerTransactionHasOneCustomerTx) Replace(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a headerTransactionHasOneCustomerTx) Delete(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a headerTransactionHasOneCustomerTx) Clear() error {
	return a.tx.Clear()
}

func (a headerTransactionHasOneCustomerTx) Count() int64 {
	return a.tx.Count()
}

func (a headerTransactionHasOneCustomerTx) Unscoped() *headerTransactionHasOneCustomerTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type headerTransactionDo struct{ gen.DO }

type IHeaderTransactionDo interface {
	gen.SubQuery
	Debug() IHeaderTransactionDo
	WithContext(ctx context.Context) IHeaderTransactionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHeaderTransactionDo
	WriteDB() IHeaderTransactionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHeaderTransactionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHeaderTransactionDo
	Not(conds ...gen.Condition) IHeaderTransactionDo
	Or(conds ...gen.Condition) IHeaderTransactionDo
	Select(conds ...field.Expr) IHeaderTransactionDo
	Where(conds ...gen.Condition) IHeaderTransactionDo
	Order(conds ...field.Expr) IHeaderTransactionDo
	Distinct(cols ...field.Expr) IHeaderTransactionDo
	Omit(cols ...field.Expr) IHeaderTransactionDo
	Join(table schema.Tabler, on ...field.Expr) IHeaderTransactionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHeaderTransactionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHeaderTransactionDo
	Group(cols ...field.Expr) IHeaderTransactionDo
	Having(conds ...gen.Condition) IHeaderTransactionDo
	Limit(limit int) IHeaderTransactionDo
	Offset(offset int) IHeaderTransactionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHeaderTransactionDo
	Unscoped() IHeaderTransactionDo
	Create(values ...*model.HeaderTransaction) error
	CreateInBatches(values []*model.HeaderTransaction, batchSize int) error
	Save(values ...*model.HeaderTransaction) error
	First() (*model.HeaderTransaction, error)
	Take() (*model.HeaderTransaction, error)
	Last() (*model.HeaderTransaction, error)
	Find() ([]*model.HeaderTransaction, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HeaderTransaction, err error)
	FindInBatches(result *[]*model.HeaderTransaction, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.HeaderTransaction) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHeaderTransactionDo
	Assign(attrs ...field.AssignExpr) IHeaderTransactionDo
	Joins(fields ...field.RelationField) IHeaderTransactionDo
	Preload(fields ...field.RelationField) IHeaderTransactionDo
	FirstOrInit() (*model.HeaderTransaction, error)
	FirstOrCreate() (*model.HeaderTransaction, error)
	FindByPage(offset int, limit int) (result []*model.HeaderTransaction, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHeaderTransactionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h headerTransactionDo) Debug() IHeaderTransactionDo {
	return h.withDO(h.DO.Debug())
}

func (h headerTransactionDo) WithContext(ctx context.Context) IHeaderTransactionDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h headerTransactionDo) ReadDB() IHeaderTransactionDo {
	return h.Clauses(dbresolver.Read)
}

func (h headerTransactionDo) WriteDB() IHeaderTransactionDo {
	return h.Clauses(dbresolver.Write)
}

func (h headerTransactionDo) Session(config *gorm.Session) IHeaderTransactionDo {
	return h.withDO(h.DO.Session(config))
}

func (h headerTransactionDo) Clauses(conds ...clause.Expression) IHeaderTransactionDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h headerTransactionDo) Returning(value interface{}, columns ...string) IHeaderTransactionDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h headerTransactionDo) Not(conds ...gen.Condition) IHeaderTransactionDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h headerTransactionDo) Or(conds ...gen.Condition) IHeaderTransactionDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h headerTransactionDo) Select(conds ...field.Expr) IHeaderTransactionDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h headerTransactionDo) Where(conds ...gen.Condition) IHeaderTransactionDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h headerTransactionDo) Order(conds ...field.Expr) IHeaderTransactionDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h headerTransactionDo) Distinct(cols ...field.Expr) IHeaderTransactionDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h headerTransactionDo) Omit(cols ...field.Expr) IHeaderTransactionDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h headerTransactionDo) Join(table schema.Tabler, on ...field.Expr) IHeaderTransactionDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h headerTransactionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHeaderTransactionDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h headerTransactionDo) RightJoin(table schema.Tabler, on ...field.Expr) IHeaderTransactionDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h headerTransactionDo) Group(cols ...field.Expr) IHeaderTransactionDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h headerTransactionDo) Having(conds ...gen.Condition) IHeaderTransactionDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h headerTransactionDo) Limit(limit int) IHeaderTransactionDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h headerTransactionDo) Offset(offset int) IHeaderTransactionDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h headerTransactionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHeaderTransactionDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h headerTransactionDo) Unscoped() IHeaderTransactionDo {
	return h.withDO(h.DO.Unscoped())
}

func (h headerTransactionDo) Create(values ...*model.HeaderTransaction) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h headerTransactionDo) CreateInBatches(values []*model.HeaderTransaction, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h headerTransactionDo) Save(values ...*model.HeaderTransaction) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h headerTransactionDo) First() (*model.HeaderTransaction, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HeaderTransaction), nil
	}
}

func (h headerTransactionDo) Take() (*model.HeaderTransaction, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HeaderTransaction), nil
	}
}

func (h headerTransactionDo) Last() (*model.HeaderTransaction, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HeaderTransaction), nil
	}
}

func (h headerTransactionDo) Find() ([]*model.HeaderTransaction, error) {
	result, err := h.DO.Find()
	return result.([]*model.HeaderTransaction), err
}

func (h headerTransactionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HeaderTransaction, err error) {
	buf := make([]*model.HeaderTransaction, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h headerTransactionDo) FindInBatches(result *[]*model.HeaderTransaction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h headerTransactionDo) Attrs(attrs ...field.AssignExpr) IHeaderTransactionDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h headerTransactionDo) Assign(attrs ...field.AssignExpr) IHeaderTransactionDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h headerTransactionDo) Joins(fields ...field.RelationField) IHeaderTransactionDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h headerTransactionDo) Preload(fields ...field.RelationField) IHeaderTransactionDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h headerTransactionDo) FirstOrInit() (*model.HeaderTransaction, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HeaderTransaction), nil
	}
}

func (h headerTransactionDo) FirstOrCreate() (*model.HeaderTransaction, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HeaderTransaction), nil
	}
}

func (h headerTransactionDo) FindByPage(offset int, limit int) (result []*model.HeaderTransaction, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h headerTransactionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h headerTransactionDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h headerTransactionDo) Delete(models ...*model.HeaderTransaction) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *headerTransactionDo) withDO(do gen.Dao) *headerTransactionDo {
	h.DO = *do.(*gen.DO)
	return h
}
