// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"KAIA-BE/model"
)

func newWishlist(db *gorm.DB, opts ...gen.DOOption) wishlist {
	_wishlist := wishlist{}

	_wishlist.wishlistDo.UseDB(db, opts...)
	_wishlist.wishlistDo.UseModel(&model.Wishlist{})

	tableName := _wishlist.wishlistDo.TableName()
	_wishlist.ALL = field.NewAsterisk(tableName)
	_wishlist.UserID = field.NewString(tableName, "user_id")
	_wishlist.ProductID = field.NewString(tableName, "product_id")
	_wishlist.CreatedAt = field.NewTime(tableName, "created_at")
	_wishlist.Product = wishlistHasOneProduct{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Product", "model.Product"),
		Admin: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Product.Admin", "model.Admin"),
		},
		ProductSlices: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Product.ProductSlices", "model.Productslice"),
		},
	}

	_wishlist.User = wishlistHasOneUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "model.User"),
	}

	_wishlist.fillFieldMap()

	return _wishlist
}

type wishlist struct {
	wishlistDo

	ALL       field.Asterisk
	UserID    field.String
	ProductID field.String
	CreatedAt field.Time
	Product   wishlistHasOneProduct

	User wishlistHasOneUser

	fieldMap map[string]field.Expr
}

func (w wishlist) Table(newTableName string) *wishlist {
	w.wishlistDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w wishlist) As(alias string) *wishlist {
	w.wishlistDo.DO = *(w.wishlistDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *wishlist) updateTableName(table string) *wishlist {
	w.ALL = field.NewAsterisk(table)
	w.UserID = field.NewString(table, "user_id")
	w.ProductID = field.NewString(table, "product_id")
	w.CreatedAt = field.NewTime(table, "created_at")

	w.fillFieldMap()

	return w
}

func (w *wishlist) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *wishlist) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 5)
	w.fieldMap["user_id"] = w.UserID
	w.fieldMap["product_id"] = w.ProductID
	w.fieldMap["created_at"] = w.CreatedAt

}

func (w wishlist) clone(db *gorm.DB) wishlist {
	w.wishlistDo.ReplaceConnPool(db.Statement.ConnPool)
	w.Product.db = db.Session(&gorm.Session{Initialized: true})
	w.Product.db.Statement.ConnPool = db.Statement.ConnPool
	w.User.db = db.Session(&gorm.Session{Initialized: true})
	w.User.db.Statement.ConnPool = db.Statement.ConnPool
	return w
}

func (w wishlist) replaceDB(db *gorm.DB) wishlist {
	w.wishlistDo.ReplaceDB(db)
	w.Product.db = db.Session(&gorm.Session{})
	w.User.db = db.Session(&gorm.Session{})
	return w
}

type wishlistHasOneProduct struct {
	db *gorm.DB

	field.RelationField

	Admin struct {
		field.RelationField
	}
	ProductSlices struct {
		field.RelationField
	}
}

func (a wishlistHasOneProduct) Where(conds ...field.Expr) *wishlistHasOneProduct {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a wishlistHasOneProduct) WithContext(ctx context.Context) *wishlistHasOneProduct {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a wishlistHasOneProduct) Session(session *gorm.Session) *wishlistHasOneProduct {
	a.db = a.db.Session(session)
	return &a
}

func (a wishlistHasOneProduct) Model(m *model.Wishlist) *wishlistHasOneProductTx {
	return &wishlistHasOneProductTx{a.db.Model(m).Association(a.Name())}
}

func (a wishlistHasOneProduct) Unscoped() *wishlistHasOneProduct {
	a.db = a.db.Unscoped()
	return &a
}

type wishlistHasOneProductTx struct{ tx *gorm.Association }

func (a wishlistHasOneProductTx) Find() (result *model.Product, err error) {
	return result, a.tx.Find(&result)
}

func (a wishlistHasOneProductTx) Append(values ...*model.Product) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a wishlistHasOneProductTx) Replace(values ...*model.Product) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a wishlistHasOneProductTx) Delete(values ...*model.Product) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a wishlistHasOneProductTx) Clear() error {
	return a.tx.Clear()
}

func (a wishlistHasOneProductTx) Count() int64 {
	return a.tx.Count()
}

func (a wishlistHasOneProductTx) Unscoped() *wishlistHasOneProductTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type wishlistHasOneUser struct {
	db *gorm.DB

	field.RelationField
}

func (a wishlistHasOneUser) Where(conds ...field.Expr) *wishlistHasOneUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a wishlistHasOneUser) WithContext(ctx context.Context) *wishlistHasOneUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a wishlistHasOneUser) Session(session *gorm.Session) *wishlistHasOneUser {
	a.db = a.db.Session(session)
	return &a
}

func (a wishlistHasOneUser) Model(m *model.Wishlist) *wishlistHasOneUserTx {
	return &wishlistHasOneUserTx{a.db.Model(m).Association(a.Name())}
}

func (a wishlistHasOneUser) Unscoped() *wishlistHasOneUser {
	a.db = a.db.Unscoped()
	return &a
}

type wishlistHasOneUserTx struct{ tx *gorm.Association }

func (a wishlistHasOneUserTx) Find() (result *model.User, err error) {
	return result, a.tx.Find(&result)
}

func (a wishlistHasOneUserTx) Append(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a wishlistHasOneUserTx) Replace(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a wishlistHasOneUserTx) Delete(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a wishlistHasOneUserTx) Clear() error {
	return a.tx.Clear()
}

func (a wishlistHasOneUserTx) Count() int64 {
	return a.tx.Count()
}

func (a wishlistHasOneUserTx) Unscoped() *wishlistHasOneUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type wishlistDo struct{ gen.DO }

type IWishlistDo interface {
	gen.SubQuery
	Debug() IWishlistDo
	WithContext(ctx context.Context) IWishlistDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWishlistDo
	WriteDB() IWishlistDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWishlistDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWishlistDo
	Not(conds ...gen.Condition) IWishlistDo
	Or(conds ...gen.Condition) IWishlistDo
	Select(conds ...field.Expr) IWishlistDo
	Where(conds ...gen.Condition) IWishlistDo
	Order(conds ...field.Expr) IWishlistDo
	Distinct(cols ...field.Expr) IWishlistDo
	Omit(cols ...field.Expr) IWishlistDo
	Join(table schema.Tabler, on ...field.Expr) IWishlistDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWishlistDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWishlistDo
	Group(cols ...field.Expr) IWishlistDo
	Having(conds ...gen.Condition) IWishlistDo
	Limit(limit int) IWishlistDo
	Offset(offset int) IWishlistDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWishlistDo
	Unscoped() IWishlistDo
	Create(values ...*model.Wishlist) error
	CreateInBatches(values []*model.Wishlist, batchSize int) error
	Save(values ...*model.Wishlist) error
	First() (*model.Wishlist, error)
	Take() (*model.Wishlist, error)
	Last() (*model.Wishlist, error)
	Find() ([]*model.Wishlist, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Wishlist, err error)
	FindInBatches(result *[]*model.Wishlist, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Wishlist) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWishlistDo
	Assign(attrs ...field.AssignExpr) IWishlistDo
	Joins(fields ...field.RelationField) IWishlistDo
	Preload(fields ...field.RelationField) IWishlistDo
	FirstOrInit() (*model.Wishlist, error)
	FirstOrCreate() (*model.Wishlist, error)
	FindByPage(offset int, limit int) (result []*model.Wishlist, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWishlistDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w wishlistDo) Debug() IWishlistDo {
	return w.withDO(w.DO.Debug())
}

func (w wishlistDo) WithContext(ctx context.Context) IWishlistDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w wishlistDo) ReadDB() IWishlistDo {
	return w.Clauses(dbresolver.Read)
}

func (w wishlistDo) WriteDB() IWishlistDo {
	return w.Clauses(dbresolver.Write)
}

func (w wishlistDo) Session(config *gorm.Session) IWishlistDo {
	return w.withDO(w.DO.Session(config))
}

func (w wishlistDo) Clauses(conds ...clause.Expression) IWishlistDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w wishlistDo) Returning(value interface{}, columns ...string) IWishlistDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w wishlistDo) Not(conds ...gen.Condition) IWishlistDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w wishlistDo) Or(conds ...gen.Condition) IWishlistDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w wishlistDo) Select(conds ...field.Expr) IWishlistDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w wishlistDo) Where(conds ...gen.Condition) IWishlistDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w wishlistDo) Order(conds ...field.Expr) IWishlistDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w wishlistDo) Distinct(cols ...field.Expr) IWishlistDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w wishlistDo) Omit(cols ...field.Expr) IWishlistDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w wishlistDo) Join(table schema.Tabler, on ...field.Expr) IWishlistDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w wishlistDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWishlistDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w wishlistDo) RightJoin(table schema.Tabler, on ...field.Expr) IWishlistDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w wishlistDo) Group(cols ...field.Expr) IWishlistDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w wishlistDo) Having(conds ...gen.Condition) IWishlistDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w wishlistDo) Limit(limit int) IWishlistDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w wishlistDo) Offset(offset int) IWishlistDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w wishlistDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWishlistDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w wishlistDo) Unscoped() IWishlistDo {
	return w.withDO(w.DO.Unscoped())
}

func (w wishlistDo) Create(values ...*model.Wishlist) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w wishlistDo) CreateInBatches(values []*model.Wishlist, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w wishlistDo) Save(values ...*model.Wishlist) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w wishlistDo) First() (*model.Wishlist, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Wishlist), nil
	}
}

func (w wishlistDo) Take() (*model.Wishlist, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Wishlist), nil
	}
}

func (w wishlistDo) Last() (*model.Wishlist, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Wishlist), nil
	}
}

func (w wishlistDo) Find() ([]*model.Wishlist, error) {
	result, err := w.DO.Find()
	return result.([]*model.Wishlist), err
}

func (w wishlistDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Wishlist, err error) {
	buf := make([]*model.Wishlist, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w wishlistDo) FindInBatches(result *[]*model.Wishlist, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w wishlistDo) Attrs(attrs ...field.AssignExpr) IWishlistDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w wishlistDo) Assign(attrs ...field.AssignExpr) IWishlistDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w wishlistDo) Joins(fields ...field.RelationField) IWishlistDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w wishlistDo) Preload(fields ...field.RelationField) IWishlistDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w wishlistDo) FirstOrInit() (*model.Wishlist, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Wishlist), nil
	}
}

func (w wishlistDo) FirstOrCreate() (*model.Wishlist, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Wishlist), nil
	}
}

func (w wishlistDo) FindByPage(offset int, limit int) (result []*model.Wishlist, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w wishlistDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w wishlistDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w wishlistDo) Delete(models ...*model.Wishlist) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *wishlistDo) withDO(do gen.Dao) *wishlistDo {
	w.DO = *do.(*gen.DO)
	return w
}
